server:
  env: local
  port: 8888
  app_name: gin-app
  app_url: http://localhost

log:
  level: info
  root_dir: ./log/logs
  filename: app.log
  format:
  show_line: true
  max_backups: 100
  max_size: 500
  max_age: 28
  compress: true

mysqlDatabase:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: workflow_management
  username: root
  password: 123456
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
  enable_file_log_writer: true
  log_filename: mysql.log